### ISSUE TITLE
RuntimeError: jpeg_loader: error while loading image

### ISSUE THREAD

**Issue by shawntz** [agporto/ml-morph#1]
Hi @agporto, I've been trying to test out your program with a simple training set, but I seem to get this error after configuring everything:
```
Traceback (most recent call last):
  File "detector_trainer.py", line 44, in <module>
    dlib.train_simple_object_detector(train_path, args['out']+".svm", options)
RuntimeError: jpeg_loader: error while loading image: Wrong JPEG library version: library is 90, caller expects 80
```

Wondering if you could provide some insights or suggestions, thanks!

**Comment by agporto** [comment]
Hi Shawn. My initial guess would be that opencv (one of the ml-morph dependencies) is expecting to find libjpeg 80 and is finding a more recent version (90) instead. This thread might have some suggestions on how to fix it: https://github.com/jcjohnson/neural-style/issues/132 
If you provide more info on your system (OS; python version and the versions of the libraries you are using), I might be able to help a little more.
